version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: default
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080